FROM python:3.7-alpine3.10 as alpine
RUN apk add g++ lapack-dev gfortran && \
    pip3 install numpy pandas scipy==1.3.1 Cython scikit-learn==0.21.1


ARG OCCLUM_VERSION
FROM occlum/occlum:$OCCLUM_VERSION-ubuntu18.04 as base
LABEL maintainer="Chunyang Hui <sanqian.hcy@antgroup.com>"

WORKDIR /root/demos/python
COPY --from=alpine /root /root/alpine_python

WORKDIR /root
