resource_limits:
  num_of_cpus: 128
  kernel_space_stack_size: 1MB
  kernel_space_heap_size:
    init: 32MB
    max: 512MB
  user_space_size:
    init: 300MB
    max: 64GB
process:
  default_stack_size: 4MB
  default_heap_size: 32MB
entry_points:
  - /bin
env:
  default:
    - OCCLUM=yes
  untrusted:
    - EXAMPLE
metadata:
  product_id: 0
  version_number: 0
  debuggable: true
  enable_kss: true
  ext_prod_id:
    high: '0x0'
    low: '0x0'
  pkru: 0
mount:
  - target: /
    type: unionfs
    options:
      layers:
        - target: /
          type: sefs
          source: ./build/mount/__ROOT
          options:
            MAC: ''
        - target: /
          type: sefs
          source: ./run/mount/__ROOT
  - target: /host
    type: hostfs
    source: .
