LABEL maintainer="Chunyang Hui <sanqian.hcy@antgroup.com>"

FROM jessehui/occlum:legacy-occlum-ubuntu20.04-edmm-experiment-2.19

ARG OCCLUM_BRANCH
WORKDIR /root
RUN git clone -b $OCCLUM_BRANCH https://github.com/occlum/occlum && \
    cd occlum && \
    source /opt/intel/sgxsdk/environment && \
    make submodule && \
    OCCLUM_RELEASE_BUILD=1 make install && \
    cp -r demos /root/demos && \
    rm -rf /root/occlum
