# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ all ]
  pull_request:
    branches: [ all ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    env:
        OCCLUM_VERSION: 0.13.0
    container: occlum/occlum:$OCCLUM_VERSION

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        
    - name: Set up environment
      run: source /opt/intel/sgxsdk/environment
        
    # Runs a set of commands using the runners shell
    - name: Check format
      run: |
        cd $GITHUB_WORKSPACE
        info=$(make format-check)
        if [ -n "$info" ]; then 
          echo "Format error detected."; 
          exit 1;
        fi
        
    - name: Build dependencies
      run: |
        cd $GITHUB_WORKSPACE
        make submodule
      
    - name: Build src
      run: |
        cd $GITHUB_WORKSPACE
        OCCLUM_RELEASE_BUILD=y SGX_MODE=SIM make
        
    - name: Integration test
      run: |
        cd $GITHUB_WORKSPACE
        SGX_MODE=SIM make test













